/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDepositVerifier,
  IDepositVerifierInterface,
} from "../../AintiVirusMixer.sol/IDepositVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "_pA",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "_pB",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "_pC",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[5]",
        name: "_pubSignals",
        type: "uint256[5]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDepositVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IDepositVerifierInterface {
    return new Interface(_abi) as IDepositVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDepositVerifier {
    return new Contract(address, _abi, runner) as unknown as IDepositVerifier;
  }
}
